image:
  file: .gitpod/.gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: notify
    visibility: public

tasks:
  - name: 'Install Node Modules'
    init: |
        npm ci

  - name: 'Install VSCode Extensions'
    init: |
        code --install-extension /vscode-extensions/cucumber-official.vsix

  - name: 'Serve reports'
    # Starting HTTP server in the background, so it doesn't block pre-builds
    before: >
      mkdir -p target/site/serenity &&
      (http-server target/site/serenity -p 8000 &)

  - name: 'Welcome'
    command: |
      echo "To run tests: npm test"
      echo "Check out the reports at"
      gp url 8000

vscode:
  extensions:
    - EditorConfig.EditorConfig
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    # - CucumberOpen.cucumber-official  # pending: https://github.com/cucumber/vscode/issues/98
