image:
  file: .gitpod/gitpod.Dockerfile

tasks:
  - name: 'Install'
    init: |
      nvm install 
      npm ci
      gp sync-done installation

  - name: 'Test'
    init: gp sync-await installation
    command: |
      npm test
      gp sync-done test

  - name: 'Serve reports'
    command: |
      gp sync-await test
      http-server target/site/serenity -p 8000

  - name: 'Welcome'
    command: |
      echo "Running tests..."
      gp sync-await test
      echo "Check out Serenity BDD test report at"
      gp url 8000

ports:
  - port: 8000
    onOpen: notify
    visibility: public
