image:
  file: .gitpod/gitpod.Dockerfile

tasks:
  - name: 'Install dependencies'
    init: |
      nvm install
      npm ci
    command: npx playwright --version

  - name: 'Welcome'
    command: echo "hello"
