image:
  file: .gitpod/.gitpod.Dockerfile

tasks:
  - name: 'Install'
    init: |
      npm ci
      npx --yes playwright install

  - name: 'Serve reports'
    init: |
      mkdir -p target/site/serenity
      cp .gitpod/index.html target/site/serenity
      http-server target/site/serenity -p 8000 &

  - name: 'Welcome'
    command: |
      echo "To run tests: npm test"
      echo "Check out the reports at"
      gp url 8000

ports:
  - port: 8000
    onOpen: notify
    visibility: public
