tasks:
  - name: 'Set up os-level dependencies'
    init: |
      sudo apt-get install dialog

  - name: 'Set up Node'
    init: |
      nvm install
      npm ci 

  - name: 'Install Playwright'
    init: |
      npx playwright install --with-deps
