image:
  file: .gitpod/gitpod.Dockerfile

tasks:
  - name: 'Setup Node'
    before: |
      nvm install
      npm ci
      gp sync-done setup-node

  - name: 'Test'
    init: gp sync-await setup-node
    command: |
      cd target/site/serenity
      http-server -p 8000 &
      cd ../../../

  - name: 'Welcome'
    init: gp sync-await setup-node
    command: echo "Setup Node finished"

ports:
  - port: 8000
    onOpen: notify
    visibility: public
