image:
  file: .gitpod/.gitpod.Dockerfile

ports:
  - port: 8000
    onOpen: notify
    visibility: public

tasks:
  - name: 'Install'
    init: >
      npm ci &&
      gp sync-done npm-ci

  - name: 'Serve reports'
    # Starting HTTP server in the background, so it doesn't block pre-builds
    before: >
      mkdir -p target/site/serenity &&
      cp .gitpod/index.html target/site/serenity &&
      (http-server target/site/serenity -p 8000 &)

  - name: 'Welcome'
    init: gp sync-await npm-ci
    command: |
      echo "To run tests: npm test"
      echo "Check out the reports at"
      gp url 8000
