image:
  file: .gitpod/gitpod.Dockerfile

tasks:
  - name: 'Install dependencies'
    before: |
      nvm install
      npm ci
      npx --yes playwright install --with-deps
      gp sync-done installation
    init: |
      npm test
    command: npx playwright --version

  - name: 'Welcome'
    init: gp sync-await installation
    command: echo "hello"
