image:
  file: .gitpod/gitpod.Dockerfile

tasks:
  - name: 'Setup Node'
    before: |
      nvm install
      npm ci
      gp sync-done setup-node

  - name: 'Test'
    init: gp sync-await setup-node
    command: |
      npm test
      gp sync-done test

  - name: 'Serve reports'
    init: |
      gp sync-await setup-node
      gp sync-done test
    command: |
      http-server target/site/serenity -p 8000

  - name: 'Welcome'
    init:
      echo "Setting up Node.js..."
      gp sync-await setup-node
      echo "Running tests..."
      gp sync-await test
      echo "All done!"
    command: gp url 8000

ports:
  - port: 8000
    onOpen: notify
    visibility: public
