image:
  file: .gitpod/gitpod.Dockerfile

tasks:
  - name: 'Setup Node'
    before: |
      nvm install
      npm ci
      gp sync-done setup-node
#    init: |
#      npx --yes playwright install --with-deps
#    command: npx playwright --version

  - name: 'Welcome'
    init: gp sync-await setup-node
    command: echo "Setup Node finished"
