tasks:
  - name: 'Install dependencies'
    init: |
      sudo apt-get install dialog &&
      nvm install &&
      npm ci &&
      npx --yes playwright install-deps &&
      npx --yes playwright install
